language: python
python:
  - "2.7"
  - "3.3"
env:
  # - SUBLIME_TEXT_VERSION="2.0"
  - SUBLIME_TEXT_VERSION="3.0"

install:
  - export SUBLIME_TESTS_AUTO_KILL=TRUE
  # Install Sublime Text
  - ./test/install.sh

  # List Sublime Text info for debugging
  - sublime_text --version

  # Install `sublime_plugin_tests`
  - python setup.py develop

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
