language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  # http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2
  - sudo add-apt-repository ppa:webupd8team/sublime-text-2 -y
  - sudo apt-get update
  - sudo apt-get install sublime-text -y
  - sudo ln -s /usr/bin/subl /usr/bin/sublime_text

  # List Sublime Text info for debugging
  - sublime_text --version

  # Install `sublime_plugin_tests`
  - python setup.py install

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start -extension RANDR"

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
