language: python
python:
  - "2.7"
env:
  - SUBLIME_TEXT_VERSION="2.0"
  # - SUBLIME_TEXT_VERSION="3.0"

install:
  # Install Sublime Text
  - ./test/install.sh

  # List Sublime Text info for debugging
  - sublime_text --version

  # Install `sublime_plugin_tests`
  - python setup.py install

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - uname --all
  - env

script:
  # Run our tests
  - SUBLIME_TESTS_AUTO_KILL=TRUE ./test.sh

notifications:
  email: false
